git:
  depth: false
language: java
jdk: oraclejdk11
script: "./gradlew openApiGenerate && ./gradlew test"
after_success:
    - "./gradlew jacocoTestReport"
    - bash <(curl -s https://codecov.io/bash)
